# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'glyph_view.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(775, 600)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout.addWidget(self.groupBox_2)
        self.frame_load = QtWidgets.QHBoxLayout()
        self.frame_load.setContentsMargins(0, 8, 0, 8)
        self.frame_load.setObjectName("frame_load")
        self.label_info = QtWidgets.QLabel(self.frame)
        self.label_info.setObjectName("label_info")
        self.frame_load.addWidget(self.label_info)
        self.label_status = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_status.setFont(font)
        self.label_status.setText("")
        self.label_status.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_status.setObjectName("label_status")
        self.frame_load.addWidget(self.label_status)
        self.button_load = QtWidgets.QPushButton(self.frame)
        self.button_load.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.button_load.setCheckable(False)
        self.button_load.setObjectName("button_load")
        self.frame_load.addWidget(self.button_load)
        self.verticalLayout.addLayout(self.frame_load)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout.addWidget(self.groupBox)
        self.frame_parameters = QtWidgets.QHBoxLayout()
        self.frame_parameters.setContentsMargins(0, 8, 0, 8)
        self.frame_parameters.setObjectName("frame_parameters")
        self.label_radius = QtWidgets.QLabel(self.frame)
        self.label_radius.setObjectName("label_radius")
        self.frame_parameters.addWidget(self.label_radius)
        self.line_radius = QtWidgets.QLineEdit(self.frame)
        self.line_radius.setObjectName("line_radius")
        self.frame_parameters.addWidget(self.line_radius)
        self.label_angle = QtWidgets.QLabel(self.frame)
        self.label_angle.setObjectName("label_angle")
        self.frame_parameters.addWidget(self.label_angle)
        self.line_angle = QtWidgets.QLineEdit(self.frame)
        self.line_angle.setObjectName("line_angle")
        self.frame_parameters.addWidget(self.line_angle)
        self.verticalLayout.addLayout(self.frame_parameters)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout.addWidget(self.groupBox_3)
        self.combo_type = QtWidgets.QComboBox(self.frame)
        self.combo_type.setObjectName("combo_type")
        self.combo_type.addItem("")
        self.combo_type.addItem("")
        self.combo_type.addItem("")
        self.verticalLayout.addWidget(self.combo_type)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout.addWidget(self.groupBox_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 8, -1, 8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.check_ground = QtWidgets.QCheckBox(self.frame)
        self.check_ground.setChecked(True)
        self.check_ground.setTristate(False)
        self.check_ground.setObjectName("check_ground")
        self.horizontalLayout_2.addWidget(self.check_ground)
        self.check_surface = QtWidgets.QCheckBox(self.frame)
        self.check_surface.setChecked(True)
        self.check_surface.setObjectName("check_surface")
        self.horizontalLayout_2.addWidget(self.check_surface)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit.setEnabled(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.button_run = QtWidgets.QPushButton(self.frame)
        self.button_run.setObjectName("button_run")
        self.verticalLayout.addWidget(self.button_run)
        self.vtk_panel = QtWidgets.QFrame(self.splitter)
        self.vtk_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.vtk_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.vtk_panel.setObjectName("vtk_panel")
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 775, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
	    _translate = QtCore.QCoreApplication.translate
	    MainWindow.setWindowTitle(_translate("MainWindow", "GlyphViewer"))
	    self.groupBox_2.setTitle(_translate("MainWindow", "1) Load"))
	    self.label_info.setText(_translate("MainWindow", "Load Points (.xyz/.pts)"))
	    self.button_load.setText(_translate("MainWindow", "Load file"))
	    self.groupBox.setTitle(_translate("MainWindow", "2) Parameters"))
	    self.label_radius.setText(_translate("MainWindow", "Radius(m):"))
	    self.line_radius.setText(_translate("MainWindow", "0.5"))
	    self.label_angle.setText(_translate("MainWindow", "Angle(Deg):"))
	    self.line_angle.setText(_translate("MainWindow", "15"))
	    self.groupBox_3.setTitle(_translate("MainWindow", "3) Database Type"))
	    self.combo_type.setItemText(0, _translate("MainWindow", "PointCloud"))
	    self.combo_type.setItemText(1, _translate("MainWindow", "EqualCells"))
	    self.combo_type.setItemText(2, _translate("MainWindow", "K-d tree"))
	    self.groupBox_4.setTitle(_translate("MainWindow", "4) Results"))
	    self.check_ground.setText(_translate("MainWindow", "Show ground points"))
	    self.check_surface.setText(_translate("MainWindow", "Show object points"))
	    self.plainTextEdit.setPlainText(_translate("MainWindow", "Usage:\n"
	                                                             "1) Load points file .xyz or .pts with data rows only\n"
	                                                             "2) Choose radius between 0 and 100m and angle between 0 and 90deg\n"
	                                                             "3) Choose database type\n"
	                                                             "4) Choose to show or hide come of the points\n"
	                                                             "5) Run"))
	    self.button_run.setText(_translate("MainWindow", "Run"))
